[package]
name = "stratego-exec"
version = "0.1.0"
authors = ["Rolf1e <tigran.slama@laposte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stratego-lib = { path = "../stratego-lib" }
lazy_static = "1.4.0"
