name: Manual Run Python Tests
on: workflow_dispatch  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r game-engine/requirements.txt
      - name: compile lib
        run: |
          cargo build --release --manifest-path game-engine/Cargo.toml
          cp game-engine/target/release/libstratego_lib.so ai_python/src
          mv ai_python/src/libstratego_lib.so ai_python/src/stratego_engine.so
      - name: Run tests with pytest
        run: pytest


